// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyC3IrGpMYhKT0EzvylgYafIKiW7TYOg',
    appId: '1:65760230973:web:b7bb9b857b7fee25057454',
    messagingSenderId: '65760230973',
    projectId: 'apphab-ecb58',
    authDomain: 'apphab-ecb58.firebaseapp.com',
    storageBucket: 'apphab-ecb58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVRtQYQb5lk9ju8L3-n16QaNHHQLm1zU',
    appId: '1:65760230973:android:871eb6428e2c472a057454',
    messagingSenderId: '65760230973',
    projectId: 'apphab-ecb58',
    storageBucket: 'apphab-ecb58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0qrLRe_IU0UCD4YLFQg3Z5AN_aeVo4_o',
    appId: '1:65760230973:ios:aab8bc8e681ee375057454',
    messagingSenderId: '65760230973',
    projectId: 'apphab-ecb58',
    storageBucket: 'apphab-ecb58.firebasestorage.app',
    iosBundleId: 'com.example.apphab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0qrLRe_IU0UCD4YLFQg3Z5AN_aeVo4_o',
    appId: '1:65760230973:ios:aab8bc8e681ee375057454',
    messagingSenderId: '65760230973',
    projectId: 'apphab-ecb58',
    storageBucket: 'apphab-ecb58.firebasestorage.app',
    iosBundleId: 'com.example.apphab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyC3IrGpMYhKT0EzvylgYafIKiW7TYOg',
    appId: '1:65760230973:web:2e29a4fe72e1afb1057454',
    messagingSenderId: '65760230973',
    projectId: 'apphab-ecb58',
    authDomain: 'apphab-ecb58.firebaseapp.com',
    storageBucket: 'apphab-ecb58.firebasestorage.app',
  );
}

/*
Inicializar una App
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);*/